#
# Module manifest for module 'Escape'
#
# Generated by: James Brundage
#
# Generated on: 2/4/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Escape.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '24d562ee-b1a8-4f2f-aca8-aa92c59b88c2'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start-Automating'

# Copyright statement for this module
Copyright = '2026 Start-Automating'

# Description of the functionality provided by this module
Description = 'Escape the pain of escape sequences'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @('Escape.types.ps1xml')

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-Escape'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @('escape', 'esc')

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Escape', 'Esc'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/StartAutomating/Escape/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/StartAutomating/Escape'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Escape 0.1

Initial Release of Escape module

|Number|Title|
|-|-|
|#1|Escape is a module for Escape Sequences|
|#2|Escape build|
|#3|Get-Escape should make an escape|
|#4|Escape.Sequence.alternativeFont|
|#5|Escape.Sequence.bold|
|#6|Escape.Sequence.blink|
|#7|Escape.Sequence.reverse|
|#8|Escape.Sequence.conceal|
|#9|Escape.Sequence.crossout|
|#10|Escape.Sequence.cursorUp|
|#11|Escape.Sequence.cursorDown|
|#12|Escape.Sequence.cursorForward|
|#13|Escape.Sequence.cursorBackward|
|#14|Escape.Sequence.cursorNextLine|
|#15|Escape.Sequence.cursorPreviousLine|
|#16|Escape.Sequence.underline|
|#17|Escape.Sequence.reset|
|#18|Escape.Sequence.html|
|#19|Escape.Sequence.htmlAttribute|
|#20|Escape.Sequence.xml|
|#21|Escape.Sequence.doubleUnderline|
|#22|Escape.Sequence.normalIntensity|
|#23|Escape.Sequence.italicOff|
|#24|Escape.Sequence.underlineOff|
|#25|Escape.Sequence.blinkOff|
|#26|Escape.Sequence.proportionalSpacing|
|#27|Escape.Sequence.reverseOff|
|#28|Escape.Sequence.reveal|
|#29|Escape.Sequence.crossoutOff|
|#30|Escape.Sequence.ForegroundBlack|
|#31|Escape.Sequence.ForegroundRed|
|#32|Escape.Sequence.ForegroundGreen|
|#33|Escape.Sequence.ForegroundYellow|
|#34|Escape.Sequence.ForegroundBlue|
|#35|Escape.Sequence.ForegroundPurple|
|#36|Escape.Sequence.ForegroundCyan|
|#37|Escape.Sequence.ForegroundWhite|
|#38|Escape.Sequence.foregroundColor|
|#39|Escape.Sequence.defaultForegroundColor|
|#40|Escape.Sequence.BackgroundBlack|
|#41|Escape.Sequence.BackgroundRed|
|#42|Escape.Sequence.BackgroundGreen|
|#43|Escape.Sequence.BackgroundYellow|
|#44|Escape.Sequence.BackgroundBlue|
|#45|Escape.Sequence.BackgroundPurple|
|#46|Escape.Sequence.BackgroundCyan|
|#47|Escape.Sequence.BackgroundWhite|
|#48|Escape.Sequence.backgroundColor|
|#49|Escape.Sequence.defaultBackgroundColor|
|#50|Escape.Sequence.disableProportionalSpacing|
|#51|Escape.Sequence.framed|
|#52|Escape.Sequence.encircled|
|#53|Escape.Sequence.overline|
|#54|Escape.Sequence.notFramed|
|#55|Escape.Sequence.overlineOff|
|#56|Escape.Sequence.scrollUp|
|#57|Escape.Sequence.scrollDown|
|#58|Escape.Sequence.underlineColor|
|#59|Escape.Sequence.underlineDefault|
|#60|Escape.Sequence.ideogramUnderline|
|#61|Escape.Sequence.ideogramDoubleUnderline|
|#62|Escape.Sequence.ideogramOverline|
|#63|Escape.Sequence.ideogramDoubleOverline|
|#64|Escape.Sequence.ideogramStress|
|#65|Escape.Sequence.ideogramReset|
|#66|Escape.Sequence.italic|
|#67|Escape.Sequence.showCursor|
|#68|Escape.Sequence.hideCursor|
|#69|Escape.Sequence.enableReportingFocus|
|#70|Escape.Sequence.disableReportingFocus|
|#71|Escape.Sequence.enableAlternateScreenBuffer|
|#72|Escape.Sequence.disableAlternateScreenBuffer|
|#73|Escape.Sequence.superscript|
|#74|Escape.Sequence.subscript|
|#75|Escape.Sequence.normalscript|
|#76|Escape.Sequence.clearScreen|
|#77|Escape.Sequence.cursorSave|
|#78|Escape.Sequence.cursorRestore|
|#79|Escape.Sequence.clearToScreenEnd|
|#80|Escape.Sequence.clearToScreenStart|
|#81|Escape.Sequence.clearLine|
|#82|Escape.Sequence.clearToLineEnd|
|#83|Escape.Sequence.clearToLineStart|
|#84|Escape.Sequence.clearScreenDeleteScrollback|
|#85|Escape.Sequence.auxOn|
|#86|Escape.Sequence.auxOff|
|#87|Escape.Sequence.nextLine|
|#88|Escape.Sequence.lastLine|
|#89|Escape.Sequence.screenAlignmentPattern|
|#90|Escape.Sequence.ForegroundBrightBlack|
|#91|Escape.Sequence.ForegroundBrightRed|
|#92|Escape.Sequence.ForegroundBrightGreen|
|#93|Escape.Sequence.ForegroundBrightYellow|
|#94|Escape.Sequence.ForegroundBrightBlue|
|#95|Escape.Sequence.ForegroundBrightPurple|
|#96|Escape.Sequence.ForegroundBrightCyan|
|#97|Escape.Sequence.ForegroundBrightWhite|
|#98|Escape.Sequence.setColor|
|#99|Escape.Sequence.hyperlink|
|#100|Escape.Sequence.BackgroundBrightBlack|
|#101|Escape.Sequence.BackgroundBrightRed|
|#102|Escape.Sequence.BackgroundBrightGreen|
|#103|Escape.Sequence.BackgroundBrightYellow|
|#104|Escape.Sequence.BackgroundBrightBlue|
|#105|Escape.Sequence.BackgroundBrightPurple|
|#106|Escape.Sequence.BackgroundBrightCyan|
|#107|Escape.Sequence.BackgroundBrightWhite|
|#108|Escape.Sequence.musicNote|
|#109|Escape contributing|
|#110|Escape code of conduct|
|#111|Escape security|
|#112|Escape sponsorship|
|#113|Escape.Sequence.cursorAbsoluteLine|
|#114|Escape.Sequence.cursorRelativeLine|
|#115|Escape.Sequence.enterLineDrawMode|
|#116|Escape.Sequence.exitLineDrawMode|
|#117|Escape.Sequence.tabForegroundColor|
|#118|Escape.Sequence.tabBackgroundColor|
|#119|`Escape.Sequence.*Color` methods should allow 'random'|
|#120|Escape.Sequence.cursorShapeDefault|
|#121|Escape.Sequence.cursorShapeBar|
|#122|Escape.Sequence.cursorShapeBlock|
|#123|Escape.Sequence.cursorShapeUnderline|
|#124|Escape.Sequence.cursorShapeBlinkingUnderline|
|#125|Escape.Sequence.cursorShapeBlinkingBlock|
|#126|Escape.Sequence.cursorShapeBlinkingBar|
|#127|Escape.Sequence.cursorBlinkOn|
|#128|Escape.Sequence.cursorBlinkOff|

'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

        PSIntro = @'

### Escape Sequences

Escape sequences are a nearly unavoiable part of technology.

We often need to escape strings into other formats
(like putting `<` or `>` inside of HTML).

We also often need to use more obscure escape sequences to adjust terminal settings.

Escape is a collection of escape sequences, and the way to escape having to remember them.

### Escape Architecture

Escape is a collection of scripts that make escape sequences.

It has a relatively simple architecture:

* Each script resides in `./Types/Escape.Sequence`.
* All scripts are compiled into ScriptMethods by [EZOut](https://github.com/StartAutomating/EZout).
* `Get-Escape` exposes all of these scripts with natural syntax
* `Get-Escape` is aliased to `escape` and `esc` for easier-to-read syntax

### Escape Contributions

While Escape has over a hundred sequences, it is nowhere near a _complete_ collection.

To help make it a better one, please consider [contributing](contributing.md)
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

